### ISSUE TITLE
GD WEBP image type support is not enabled.

### ISSUE THREAD

**Issue by 917huB** [zaywalker/chevereto#1]
With 3.20.2 update the following error is reported on opening Chevereto homepage. 

```
The system has encountered errors in your server setup that must be fixed to use Chevereto:

GD WEBP image type support is not enabled.
```

Its possible to resolve by removing WEBP from supported formats in `integrity-check.php` but it would be ideal to have it supported if possible. I'm assuming this needs some tweaks to the underlying container configuration?

**Comment by zaywalker** [comment]
I can't reproduce that error. But I've added libwebp-dev in dockerfile. Could you check it's working? Currently I can't install chevereto with installer.php because the installer.php gives me system error. hmm....

**Comment by zaywalker** [comment]
Fixed! :)
